### ISSUE TITLE
Build fails on Ubuntu 20.04 via git as well as tarball

### ISSUE THREAD

**Issue by Tanmay-Chavan** [robol/MPSolve#29] opened 2021-04-10 15:18 UTC
Hi, 
I tried installing MPSolve via Git. However, it failed. `configure` executed without any error. I tried installing with tarball, but it failed again giving the same error.

The error is seems to be caused by this:
`  CXX      xmpsolve-polynomialsolver_moc.o
polynomialsolver_moc.cpp:205:18: error: ‘QMetaObject::SuperData’ has not been declared
  205 |     QMetaObject::SuperData::link<QObject::staticMetaObject>(),
      |                  ^~~~~~~~~
polynomialsolver_moc.cpp:205:61: error: expected primary-expression before ‘)’ token
  205 |     QMetaObject::SuperData::link<QObject::staticMetaObject>(),
      |                                                             ^
make[4]: *** [Makefile:933: xmpsolve-polynomialsolver_moc.o] Error 1
make[4]: Leaving directory '/home/tanmay/MPSolve/src/xmpsolve'
make[3]: *** [Makefile:598: all] Error 2`

I have a system Qt version installed along with the online installer version and a manual build (system Qt has preference).
the entire shell output can be found here: [https://pastebin.com/5JNn7Z3j](https://pastebin.com/5JNn7Z3j)

**Comment by robol** [comment] 2021-04-12 06:37
This might be caused by an inconsistency in the Qt tools used for the compilation; for instance, it is possible that you are using the moc compiler from the Qt installed got with the installer, and then trying to link with system Qt, or the other way around. 

Can you check if the selected moc binary is the right version? Try running ```moc -v```.

In addition, it could be helpful to have the output of the compilation with ```make V=1```, and the ```config.log``` generated by the configure script (the latter will be in the build directory).

**Comment by Tanmay-Chavan** [comment] 2021-04-12 17:07
`moc -v` shows 5.15.2... which is my custom Qt. 

and `make V=1` yields this after running `make clean` : [https://pastebin.com/hbcRJNBZ](https://pastebin.com/hbcRJNBZ)

I have uploaded `config.log` here:[https://github.com/Tanmay-Chavan/fluffy-couscous/blob/gh-pages/config.log]( https://github.com/Tanmay-Chavan/fluffy-couscous/blob/gh-pages/config.log)

I guess what you're saying is right, different versions of Qt must've messed it up. Guess I'll have to either change path preferences, or play around with configure.

Also, I really like your project! I am planning to use it in a KDE software. just one question, is your method more efficient than the one implemented in GSL? I know they're different approaches, and that this method guarantess to find all roots, but will it be faster than GSL?

**Comment by robol** [comment] 2021-04-12 17:49
It's possible that the heuristic to find the moc & co. binaries may be improved. In any case, you need to make sure that the various parts of Qt are from the same version. 

GSL provides the routine  gsl_poly_complex_solve, which implements a balanced QR iteration. This is the "standard" method for solving polynomial equations, and works well, but has a O(n³) complexity in the degree; for MPSolve, you should expect O(n²) for most polynomial classes. However, the setting is slightly different, as MPSolve guarantees the digits for polynomials that are known with integer or rational coefficients, whereas GSL provides a weaker guarantee, that is usually known as "backward stability": the roots will be roots of a polynomials with slightly modified coefficients. Also, memory for QR is O(n²) whereas for MPSolve it's O(n). 

But the QR iteration might still be faster for small degrees; there are implementation of QR iterations for polynomial rootfinding that only require O(n²) complexity and O(n), storage, see for instance [eiscor](https://github.com/eiscor/eiscor).

I'll close the issue for now, feel free to reopen if it's still an issue.

**Closed by robol** 2021-04-12 17:49 UTC

**Comment by Tanmay-Chavan** [comment] 2021-04-13 18:27
Thanks a lot! I'll try what you suggested.
